### ISSUE TITLE
Docker Image is stuck on 2.3

### ISSUE THREAD

**Issue by MaxRink** [pretix/pretix#1179]
The pretix/standalone:stable Image is still delivering pretix 2.3, not 2.4

**Comment by raphaelm** [comment]
Thanks for telling us, the tag didn't point correctly. I fixed it with Docker Hub and triggered an update. It might take some time until docker actually builds this: https://hub.docker.com/r/pretix/standalone/builds

**Comment by MaxRink** [comment]
I think the tagging still isnt quite right.
Right now the image gets rebuild every few hours although there is no change from the base image or within the 2.4 branch to trigger it. 
From what i see the Image for 2.4 get rebuild every time as someone commits to the master branch, which shouldnt be the case

**Comment by raphaelm** [comment]
I'm not sure what's going on here

![2019-02-20-225212_1045x505_scrot](https://user-images.githubusercontent.com/64280/53127235-4871de80-3562-11e9-8a46-6805734ac8eb.png)

**Comment by MaxRink** [comment]
This is strange. The Tags seem correct, but nevertheless the Image gets rebuild more oftenthan needed. 
Do you have any Webhooks or other integrations that could trigger Docker Hub builds?
