### ISSUE TITLE
Error message while running "upgrade" from pretix version 2.5 to 2.7

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#1282]
I am running pretix with docker and a Dockerfile. 

I followed the usual upgrade procedure. When I used the command "docker exec -it pretix.service pretix upgrade", I got the following error message: 

Pretix is running though: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pretix/src/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/pretix/src/pretix/presale/management/commands/updatestyles.py", line 38, in handle
    default_storage.delete(fname)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 297, in delete
    name = self.path(name)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 323, in path
    return safe_join(self.location, name)
  File "/usr/local/lib/python3.6/site-packages/django/utils/_os.py", line 32, in safe_join
    final_path = abspath(join(base, *paths))
  File "/usr/local/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'File'
```

**Comment by buenaventure** [comment]
I am also getting this error when I try to run `python -m pretix updatestyles`

**Comment by buenaventure** [comment]
I fixed the issue by applying 53053f19e4a56407ba150c1339ad6debbca2a259.
But @raphaelm reverted that commit in 79ae9b6501eaabc19852e6d2325839291d57beb2, so I suppose this breaks something else. @raphaelm can you help?

**Comment by raphaelm** [comment]
I still don't understand this myself. One of the version failed locally, one in prod. Apparently, the file storage returns different types in different cases, which is bad. For me, re-running the command multiple times mostly fixed the issue (because the error happens during deletion of the old stylesheet). I'll need to look into this deeper, I guess.

**Comment by raphaelm** [comment]
I just pushed another attempt to fix. @buenaventure can you try if it helps? If it does, I can release a 2.7.1.

**Comment by buenaventure** [comment]
It works on my instance, looks good :+1:
