### ISSUE TITLE
german error message in english shop

### ISSUE THREAD

**Issue by nilskamm** [pretix/pretix#2519]
**Describe the bug**
If a customer using english tries to add two or more of the same product in the cart, when the product is limited to one, the error message is shown in german in the site and the title of the browser.

**Expected behavior**
If a customer uses the shop in english, this error message should be in english. 

**Screenshots**
![error_german](https://user-images.githubusercontent.com/75222264/157252662-b8577077-7208-4212-8abf-737322b28482.PNG)

**Additional context**
We use pretix 7.4.1 in Docker.
The product has a max limit of 1 but two variants.
Because of that it is possible to order more than one.

**Comment by raphaelm** [comment]
Closing as this is very long ago and likely fixed in the meantime

**Comment by nilskamm** [comment]
Hey Raphael!
I checked it again in pretix 4.15.0 and the same problem still exists!
To be more precise how to get to this error. 
I added one product where the product itself has a max order limit of 1 to my cart. 
In the cart there is a "+" button next to the amount. 
After using it, the error message appears in german while using the rest of the shop is in english.

**Comment by wiffbi** [comment]
We are looking into this, but are having trouble recreating the error. Do you have pretix running with celery? Also, could you test it with JavaScript disabled in your browser? The cart interaction by default is an async action through JavaScript, which might have a problem somewhere with language-context.

Thanks for your help debugging this issue!

**Comment by wiffbi** [comment]
Furthermore, could you try to force other cart-errors for testing? E.g. test „Minimum amount per order“ or try an unknown voucher-code. Is the error message in german as well? Thanks!

**Comment by nilskamm** [comment]
I´m happy to help! 
We use pretix in Docker as you describe it in your "Small-scale deployment with Docker" documentation. 
Docker logs says "celery@XXX ready" so i guess celery is running.
With JavaScript disabled it also occurs in german. Tested it with Firefox and Google Chrome.
Minimum amount per order and unknown voucher code messages also appear in german.

Here is a link to our test shop: https://tickets.lost-ideas.com/icantbelieveit/
Can you recreate the error there?
"GSC Amazons" has a minimum of 2
"GSC Marauder" has a maximum of 1

**Comment by wiffbi** [comment]
Hm, I am very sorry, I could not reproduce the error even with redis and celery activated in my setup. We think it has something to do with celery and the message being serialized. To make sure, please try and deactivate celery in your `/etc/pretix/pretix.cfg` – just add `: ` at the beginning of every line under `[celery]`. Does the error still persist? Thanks again for your help!

**Comment by raphaelm** [comment]
I don't think it's related to celery at all, because the voucher redemption message is affected which doesn't go through the celery stack

**Comment by wiffbi** [comment]
I managed to at least manually get the error message to appear in german – I suspect that in `pretix/base/services/cart.py` during startup the active language is german. Due to the use of `gettext as _` in `services/cart.py` the messages are translated immediately to german and in later steps are not translated again – I only managed to switch the context to german manually though, by calling `django.utils.translation.activate('de')` before `error_messages` are defined, but with this, I could reproduce the error – page in english, errors in german. The question is, why is german the default language during startup? I could not change my setup/config so it was german on startup, but maybe you have something special? Maybe even system-language?

A quick fix was to import `gettext_lazy as _` instead of `gettext,` but I have not tested yet thoroughly to be sure.

**Comment by nilskamm** [comment]
System is an Ubuntu 20.04.5 LTS in english and the only thing i can find in our pretix.cfg is this part:
```
[locale]
default=de
```
I already put it there before i started pretix the very first time.

**Comment by wiffbi** [comment]
Oh, that seems to be it! I added that to my pretix.cfg and was able reproduce the error. I guess the solution is to use `gettext_lazy as _` instead of `gettext as _` as that fixed it for me. I am not 100% sure about other side effects so will investigate.
